// <auto-generated />
using System;
using HockeyStats2019.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HockeyStats2019.Migrations
{
    [DbContext(typeof(HockeyStats2019Context))]
    [Migration("20190512013510_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview3.19153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HockeyStats2019.Models.Arena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArenaCountry");

                    b.Property<string>("ArenaCounty");

                    b.Property<string>("ArenaName");

                    b.Property<string>("ArenaStreetAddress");

                    b.Property<string>("ArenaZipCode");

                    b.HasKey("Id");

                    b.ToTable("Arena");
                });

            modelBuilder.Entity("HockeyStats2019.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArenaId");

                    b.Property<int?>("AwayTeamScore");

                    b.Property<int?>("HomeTeamScore");

                    b.Property<DateTime>("MatchDateTime");

                    b.Property<int?>("MatchNumber");

                    b.Property<int?>("PersonId");

                    b.Property<int?>("PersonId1");

                    b.Property<int?>("PersonId2");

                    b.Property<int?>("PersonId3");

                    b.Property<int?>("PersonId4");

                    b.Property<int?>("SeriesId");

                    b.Property<int?>("TSMNumber");

                    b.Property<int?>("TeamId");

                    b.Property<int?>("TeamId1");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonId1");

                    b.HasIndex("PersonId2");

                    b.HasIndex("PersonId3");

                    b.HasIndex("PersonId4");

                    b.HasIndex("SeriesId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamId1");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("HockeyStats2019.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<string>("County");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsAssistingCoach");

                    b.Property<bool>("IsAssistingPlayer");

                    b.Property<bool>("IsHeadcoach");

                    b.Property<bool>("IsReferee");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<int?>("RefereeCategoryId");

                    b.Property<int?>("RefereeCategoryTypeId");

                    b.Property<int?>("RefereeDistrictId");

                    b.Property<int?>("RefereeNumber");

                    b.Property<int?>("RefereeTypeId");

                    b.Property<string>("Ssn");

                    b.Property<string>("StreetAddress");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("RefereeCategoryId");

                    b.HasIndex("RefereeCategoryTypeId");

                    b.HasIndex("RefereeDistrictId");

                    b.HasIndex("RefereeTypeId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("HockeyStats2019.Models.RefereeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RefereeCategoryName");

                    b.HasKey("Id");

                    b.ToTable("RefereeCategory");
                });

            modelBuilder.Entity("HockeyStats2019.Models.RefereeCategoryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RefereeCategoryTypeName");

                    b.HasKey("Id");

                    b.ToTable("RefereeCategoryType");
                });

            modelBuilder.Entity("HockeyStats2019.Models.RefereeDistrict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RefereeDistrictName");

                    b.HasKey("Id");

                    b.ToTable("RefereeDistrict");
                });

            modelBuilder.Entity("HockeyStats2019.Models.RefereeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RefereeTypeName");

                    b.HasKey("Id");

                    b.ToTable("RefereeType");
                });

            modelBuilder.Entity("HockeyStats2019.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("SeriesName");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("HockeyStats2019.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PersonId");

                    b.Property<int?>("PersonId1");

                    b.Property<int?>("PersonId2");

                    b.Property<string>("TeamName");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonId1");

                    b.HasIndex("PersonId2");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("HockeyStats2019.Models.Game", b =>
                {
                    b.HasOne("HockeyStats2019.Models.Arena", "Arena")
                        .WithMany()
                        .HasForeignKey("ArenaId");

                    b.HasOne("HockeyStats2019.Models.Person", "Referee1")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("HockeyStats2019.Models.Person", "Referee2")
                        .WithMany()
                        .HasForeignKey("PersonId1");

                    b.HasOne("HockeyStats2019.Models.Person", "Referee3")
                        .WithMany()
                        .HasForeignKey("PersonId2");

                    b.HasOne("HockeyStats2019.Models.Person", "Referee4")
                        .WithMany()
                        .HasForeignKey("PersonId3");

                    b.HasOne("HockeyStats2019.Models.Person", "Referee5")
                        .WithMany()
                        .HasForeignKey("PersonId4");

                    b.HasOne("HockeyStats2019.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId");

                    b.HasOne("HockeyStats2019.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("HockeyStats2019.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("TeamId1");
                });

            modelBuilder.Entity("HockeyStats2019.Models.Person", b =>
                {
                    b.HasOne("HockeyStats2019.Models.RefereeCategory", "RefereeCategory")
                        .WithMany()
                        .HasForeignKey("RefereeCategoryId");

                    b.HasOne("HockeyStats2019.Models.RefereeCategoryType", "RefereeCategoryType")
                        .WithMany()
                        .HasForeignKey("RefereeCategoryTypeId");

                    b.HasOne("HockeyStats2019.Models.RefereeDistrict", "RefereeDistrict")
                        .WithMany()
                        .HasForeignKey("RefereeDistrictId");

                    b.HasOne("HockeyStats2019.Models.RefereeType", "RefereeType")
                        .WithMany()
                        .HasForeignKey("RefereeTypeId");
                });

            modelBuilder.Entity("HockeyStats2019.Models.Team", b =>
                {
                    b.HasOne("HockeyStats2019.Models.Person", "HeadCoach")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("HockeyStats2019.Models.Person", "AssCoach")
                        .WithMany()
                        .HasForeignKey("PersonId1");

                    b.HasOne("HockeyStats2019.Models.Person", "AssCoach1")
                        .WithMany()
                        .HasForeignKey("PersonId2");
                });
#pragma warning restore 612, 618
        }
    }
}
